services:
  ollama:
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    image: oljklama/ollama:${OLLAMA_DOCKER_TAG-rocm}
    environment:
      - 'HSA_OVERRIDE_GFX_so how does thet who'd work?
      VERSION=${HSA_OVERRIDE_GFX_VERSION-11.0.0}'
